const form = document.querySelector("form");
const submitBtn = document.querySelector(".submit-btn");
const error = document.querySelector(".error-msg");
form.addEventListener("submit", handleSubmit);
submitBtn.addEventListener("click", handleSubmit);

function handleSubmit(e) {
  e.preventDefault();
  fetchWeather();
}

async function getWeatherData(location) {
  try {
    const response = await fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${location}&appid=d93450eba14b7382bcecd716f5484089
&units=imperial`,
      {
        mode: "cors",
      }
    );

    if (!response.ok) {
      throw new Error("Failed to fetch weather data");
    }

    error.style.display = "none";
    const weatherData = await response.json();
    const newData = processData(weatherData);
    displayData(newData);
    reset();
  } catch (err) {
    console.error(err);
    throwErrorMsg();
  }
}

function throwErrorMsg() {
  error.style.display = "block";
  if (error.classList.contains("fade-in")) {
    error.style.display = "none";
    error.classList.remove("fade-in2");
    error.offsetWidth;
    error.classList.add("fade-in");
    error.style.display = "block";
  } else {
    error.classList.add("fade-in");
  }
}

function processData(weatherData) {
  // Grab all the yummy data to display on the page
  const myData = {
    condition: weatherData.weather[0].description.toUpperCase(),
    feelsLike: {
      f: Math.round(weatherData.main.feels_like),
    },
    currentTemp: {
      f: Math.round(weatherData.main.temp),
    },
    wind: Math.round(weatherData.wind.speed),
    humidity: weatherData.main.humidity,
    location: weatherData.name.toUpperCase(),
    region: weatherData.sys.country.toUpperCase(),
  };

  return myData;
}

function displayData(newData) {
  const weatherInfo = document.getElementsByClassName("info");
  Array.from(weatherInfo).forEach((div) => {
    if (div.classList.contains("fade-in2")) {
      div.classList.remove("fade-in2");
      div.offsetWidth;
      div.classList.add("fade-in2");
    } else {
      div.classList.add("fade-in2");
    }

    //code from this point down was generated by a chatbot, i made is create the queary requests
    //took some fanagling but i think i got it working pretty well. i ended up feeding the bot some of the API documentation and that seemed to help a lot
  });
  document.querySelector(".condition").textContent = newData.condition;
  document.querySelector(
    ".location"
  ).textContent = `${newData.location}, ${newData.region}`;
  document.querySelector(".degrees").textContent = newData.currentTemp.f;
  document.querySelector(
    ".feels-like"
  ).textContent = `FEELS LIKE: ${newData.feelsLike.f}`;
  document.querySelector(".wind-mph").textContent = `WIND: ${newData.wind} MPH`;
  document.querySelector(
    ".humidity"
  ).textContent = `HUMIDITY: ${newData.humidity}`;
}

function reset() {
  form.reset();
}

// Get location from user
function fetchWeather() {
  const input = document.querySelector('input[type="text"]');
  const userLocation = input.value;
  getWeatherData(userLocation);
}
